# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0072d65cda62823fa487bd2e86cf220cdd4083fa4bb1b9c6e393cb26129220bc139d3eafbec648f0d1b4193f466bd5e17b84beff02ef31993eb2bbeb923d0530

test:
  secret_key_base: 971c59e433bc14a5b5915aa3d91a61ef731e848b678f3b84704261a325c8571ee9b9c15c74367aee775e94da73a1e91c42b7b0929fb58d197b49abb20f0877c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
